Microverse Project - Design Tear Down (UI/UX) of The Smashing Magazine Home Page
happiguru/design-teardown pull request #3
Opened 2020-07-01 20:25 UTC by happiguru

In this project, we designed a web page similar to the main web page of Smashing Magazine.
We have implement a gradient matching for the various section of the web page. 
We have also implemented all the photo animation of the web page.

2020-07-02 01:05 UTC, elmejdki requested changes
# status requires changes :recycle: 
## Great job guys :100: :clap: your clone looks identical to the original based on the layout. but you need to make just some minor changes to get it approved.

- [ ] Files not related to the project should not be committed and added to .gitignore:
![image](https://user-images.githubusercontent.com/34653764/86304524-01403700-bc07-11ea-8334-932653f69ad4.png)
![image](https://user-images.githubusercontent.com/34653764/86304506-f08fc100-bc06-11ea-9f0d-f27e36a6c99c.png)

### Please make all the required changes before you submit another code review.
## Happy Coding :tophat:

2020-07-02 01:05 UTC, elmejdki commented on index.html
> +            <div class="top-article top1">
please use for each article an article tag instead of a div, that will be more semantic for your project it's also on the requirements

2020-07-02 01:05 UTC, elmejdki commented on index.html
> +            <div class="top-article top2">
this one too, so remember to changes all of them ... etc.

2020-07-02 06:44 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello team 👋. Great job applying the changes. But you have missed some. Let's see:

- Files NOT related to the project should not be committed.
![image](https://user-images.githubusercontent.com/57726348/86324706-9588b900-bc5c-11ea-84a3-24cead825b0f.png)

### In addition to that:

- The footer should contain two image placeholders. 

#### Original
![Annotation 2020-07-02 120425](https://user-images.githubusercontent.com/57726348/86324876-d7b1fa80-bc5c-11ea-8c26-942d3cc66f02.jpg)

#### Clone
![Annotation 2020-07-02 120455](https://user-images.githubusercontent.com/57726348/86324887-dda7db80-bc5c-11ea-9d78-1522403ec100.jpg)

- There are a couple of warnings in your HTML file. Please fix them.

![image](https://user-images.githubusercontent.com/57726348/86325085-1d6ec300-bc5d-11ea-976b-450981912cd2.png)

Apply these changes and request another review.

Happy coding 👨‍💻

2020-07-02 10:44 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @happiguru @SunnySparks** 
Good job with your new submission for this project :muscle:  
Your project passes most of the requirements :clap: :clap: :clap:  
 There are just a few details to improve in your code before you can go ahead:
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition or you can create a new class.
- [ ]  For this project, make sure to use the article tag whenever possible, look for sections in your code with a title and paragraphs.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-02 10:44 UTC, andresporras3423 commented on index.html
> +                <div class="community-big">
replace div with article tag

2020-07-02 10:44 UTC, andresporras3423 commented on css/style.css
> +}
group selectors with same style definition

2020-07-02 10:44 UTC, andresporras3423 commented on css/style.css
> +}
This selector and selectors on lines 388, 405, and 493 have the same style definition. Group selectors or create a new class.

2020-07-02 16:45 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hi! It's me again 😀. You are almost there.

### There are some changes that you missed. Let's see:

- There are still some warnings in the HTML file.

  ![image](https://user-images.githubusercontent.com/57726348/86387751-49b42f00-bcb1-11ea-8749-fb9e351aca9c.png)

- Follow the DRY rule, as pointed out by the previous TSE. Check the comments below.

- There are some invalid CSS properties. Check the comments below.

2020-07-02 16:48 UTC, tirthajyoti-ghosh commented on css/style.css
> +}
DRY. All properties(except the `grid-area` property, which are also invalid) in these 3 style definitions are the same. Group them in one style definition.

2020-07-02 16:49 UTC, tirthajyoti-ghosh commented on css/style.css
> +  grid-area: "g1";
Invalid CSS property. `grid-area` doesn't accept `"g1"` as it's value.

2020-07-02 16:50 UTC, tirthajyoti-ghosh commented on css/style.css
> +  grid-area: "g2";
Invalid CSS property. `grid-area` doesn't accept `"g2"` as it's value.

2020-07-02 16:50 UTC, tirthajyoti-ghosh commented on css/style.css
> +  grid-area: "g3";
Invalid CSS property. `grid-area` doesn't accept `"g3"` as it's value.

2020-07-02 16:50 UTC, tirthajyoti-ghosh requested changes
Apply the above changes and request another review.

Happy coding 👨‍💻

2020-07-02 21:30 UTC, BrittanyBlake requested changes
### Status: Changes Required ♻️ 
****
### Hi Team! 👋 
You have done a great job implementing the changes requested by the previous TSE! 👍 You have also done a wonderful job with your project so far! It looks really good! 👏 👏 👏  There is just one issue that need to be resolved before you can move on: ⬇️ 
****

- [x] Your `.DS_Store `files are still present in your GitHub repository. Please note that just adding the file names to your `.gitignore` file will not work for the files that have already been pushed to GitHub. I have struggled with the `.DS_Store` issue for a while and I have found that [this Stack Overflow discussion](https://stackoverflow.com/questions/107701/how-can-i-remove-ds-store-files-from-a-git-repository) has been the most useful in teaching me how to remove all instances of `.DS_Store` from my repo.  
Your repository 👇 
![Screen Shot 2020-07-02 at 11 27 00 PM](https://user-images.githubusercontent.com/48804258/86410694-8ab14100-bcbb-11ea-9b0a-43114e5dc60f.png)



****
### Please make the required changes and resubmit for a new code review once you are ready 🙏

Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

2020-07-02 23:47 UTC, elmejdki approved these changes
# Status Approved :heavy_check_mark: 
## Great job guys  :100: :1st_place_medal: :clap:  thank you for making all the required changes.

now you can merge to master your project is approved.

## Happy Coding :tophat:

2020-07-03 04:32 UTC, merged

2020-07-03 04:34 UTC, happiguru commented
Pull request merged and closed